[database]
user=musicbrainz
database=musicbrainz_test
host=mbs_db_test
port=5432
;pool_mode=null
;pool_size=2
;pool_max_overflow=3
;pool_recycle=300

[testdatabase]
user=musicbrainz
database=musicbrainz_test
host=mbs_db_test
port=5432

[listen]
address=0.0.0.0
port=8081

[sentry]
dsn=

[ia]
download_prefix=//archive.org/download
