# Docker Compose file for production
version: "2"
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    volumes:
      - ./data/app:/data
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis

  nginx:
    extends:
      file: ./common.yml
      service: nginx
    links:
      - web:web
    ports:
      - "80:80"
