FROM metabrainz/python:3.13-20260216

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
                       build-essential \
                       git \
                       libpq-dev \
                       libffi-dev \
                       libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /code
WORKDIR /code

COPY . /code/
RUN uv sync --frozen --group dev
RUN cp config.default.ini config.ini

CMD dockerize -wait tcp://mbs_db_test:5432 -timeout 200s \
    sleep 5 && uv run pytest -m "" --junitxml=/data/test_report.xml \
                             --cov=artwork_redirect \
                             --cov-report xml:/data/coverage.xml
