FROM metabrainz/python:3.13-20260216

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
                       build-essential \
                       git \
                       libpq-dev \
                       libffi-dev \
                       libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN mkdir /code
WORKDIR /code

COPY pyproject.toml uv.lock /code/
RUN uv sync --frozen --group dev

COPY . /code/
RUN cp config.default.ini config.ini

CMD ["uv", "run", "python", "artwork_redirect_server.py"]
