name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: |
          docker compose -f docker/docker-compose.test.yml up --exit-code-from web_test

      - name: Copy artifacts
        if: always()
        run: |
          docker compose -f docker/docker-compose.test.yml cp web_test:/data/test_report.xml .
          docker compose -f docker/docker-compose.test.yml cp web_test:/data/coverage.xml .

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: |
            test_report.xml
            coverage.xml
